# Generated by Django 3.2.5 on 2021-07-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_idcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='nuevoUsuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('clave', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idCliente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
