# Generated by Django 3.2.5 on 2021-07-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210725_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresar',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Ingresar',
        ),
    ]
