# Generated by Django 3.2.5 on 2021-07-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210725_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='animales',
            fields=[
                ('idAnimal', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.CharField(max_length=30)),
            ],
        ),
    ]
