# Generated by Django 3.2.5 on 2021-07-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_animales'),
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('animales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animales')),
            ],
        ),
    ]
